urls.py
from demoapp.views import current_datetime
from demoapp.views import hello
from demoapp.views import hours_ahead
from django.conf.urls.defaults import *
from django.template import Context
from django.template import Template
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from demoapp.books import views
from demoapp.contact import views as abc

#urlpatterns = patterns('',
  # Example:
  # (r'^demoapp/', include('demoapp.foo.urls')),

  # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
  # to INSTALLED_APPS to enable admin documentation:
  # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

  # Uncomment the next line to enable the admin:
  # (r'^admin/(.*)', admin.site.root),
#)

urlpatterns = patterns('',
  ('^hello/$', hello),
  ('^time/$', current_datetime),
  (r'^time/plus/(\d{1,2})/$', hours_ahead),
  (r'^admin/(.*)', admin.site.root),
  (r'^search/$', views.search),
  (r'^contact/$', abc.contact),
  (r'^contact/thanks/$', abc.thanks),
)

books/models.py
from django.db import models

class Publisher(models.Model):
  name = models.CharField(max_length=30)
  address = models.CharField(max_length=50)
  city = models.CharField(max_length=60)
  state_province = models.CharField(max_length=30)
  country = models.CharField(max_length=50)
  website = models.URLField()

  def __unicode__(self):
    return self.name

class Author(models.Model):
  first_name = models.CharField(max_length=30)
  last_name = models.CharField(max_length=40)
  email = models.EmailField('e-mail', blank=True)

  def __unicode__(self):
    return self.first_name + ' ' + self.last_name

class Book(models.Model):
  title = models.CharField(max_length=100)
  authors = models.ManyToManyField(Author)
  publisher = models.ForeignKey(Publisher)
  publication_date = models.DateField(blank=True, null=True)

  def __unicode__(self):
    return self.title

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class ContactForm(forms.Form):
  subject = forms.CharField(max_length=100)
  email = forms.EmailField(required=False, label='Your e-mail address')
  message = forms.CharField(widget=forms.Textarea)

books/views.py
from demoapp.books.models import Book
from django.shortcuts import render_to_response

def search(request):
  errors = []
  if 'q' in request.GET:
    q = request.GET['q']
    if not q:
      errors.append('Enter a search term.')
    elif len(q) > 20:
      errors.append('Please enter at most 20 characters.')
    else:
      books = Book.objects.filter(title__icontains=q)
      return render_to_response('search_results.html',
        {'books': books, 'query': q})
  return render_to_response('search_form.html',
    {'errors': errors})





  

contact/views.py
from django.shortcuts import render_to_response
from demoapp.contact.forms import ContactForm
from django.core.mail import send_mail
from django.http import HttpResponseRedirect

def thanks(request):
  return render_to_response('thanks.html')

def contact(request):
  if request.method == 'POST':
    form = ContactForm(request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      send_mail(
        cd['subject'],
        cd['message'],
        cd.get('email', 'noreply@example.com'),
        ['siteowner@example.com'],
      )
      return HttpResponseRedirect('/contact/thanks/')
  else:
    form = ContactForm()
  return render_to_response('contact_form.html', {'form': form})

views.py
from django.shortcuts import render_to_response
from django.template import Context
import datetime
from django.http import HttpResponse

def hello(request):
  return HttpResponse("Hello world")

def current_datetime(request):
  now = datetime.datetime.now()
  return render_to_response('current_datetime.html', {'current_date': now})
  


def hours_ahead(request, offset):
  try:
    offset = int(offset)
  except ValueError:
    raise Http404()
  dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
  now = datetime.datetime.now()
  return render_to_response('hours_ahead.html', {'now': now, 'hour_offset': offset, 'next_time': dt})

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

templates/contact_form.html
<html>
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

templates/hours_ahead.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>Future time</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    <p> Current time is {{ now }}</p>
    <p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>

    <hr>
    <p>Thanks for visiting my site.</p>
</body>
</html>

templates/includes/nav.html
<div id="nav">
    You are in: {{ current_section }}
</div>

templates/mypage.html
<html>
<body>
{% include "includes/nav.html" %}
<h1>{{ title }}</h1>
</body>
</html>

templates/search_form.html
<html>
  <head>
    <title>Search</title>
  </head>
  <body>
    {% if errors %}
    <ul>
      {% for error in errors %}
      <li style="color:red">{{ error }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    <form action="/search/" method="get">
      <input type="text" name="q">
      <input type="submit" value="Search">
    </form>
  </body>
</html>

templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}
<a href="/search">Back</a>

templates/thanks.html
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
   Thanks
  </body>
</html>